### PR TITLE
test: add E2E testing with playwright

### PR DESCRIPTION
**Pull request by MFarabi619**
`npx playwright test --headed` or `npx playwright test --ui` or `npx playwright test`

image

### CODE REVIEW

**Comment by ngc** [comment]
Should this be failing?

**Comment by MFarabi619** [comment]
> Should this be failing?

Yes because it's missing the `.ENV` variables.

image

If you add them to the repo and configure the pipeline to read them, it should pass. Right now it can't start the server due to the missing env variables.

**Comment by MFarabi619** [comment]
@JowiAoun Do you mind looking into this since you've already been working in the area and have the .env variables. Once this goes in I can write my tests in parallel for your features.

**Review by JowiAoun — COMMENTED** [review]
Will those tests be run pre-push or exclusively in the pipeline?

**Comment by MFarabi619** [comment]
We should be able to run the same suite of tests locally, in the pipeline before the PR reviewers are notified, and in the pipeline after the PR is approved.

So we'll probably need to use different sets of environment variables. Running them locally would use dev variables, and in the pipeline/CI environment they should use staging variables.

**Comment by JowiAoun** [comment]
Great, I have added playwright to the modules & postinstall script. Looks good to me!

**Review by HasithDeAlwis — APPROVED** [review]

**Review by JowiAoun — APPROVED** [review]

**Pull request merged**
