### PR TITLE
chore: Introduce Common Open Source Tooling into Codebase to Increase Productivity and Developer Experience

### PR DESCRIPTION
**Pull request by MFarabi619**
- Set up [Commitlint](https://commitlint.js.org) to enforce [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) along with [Commitizen](https://commitizen-tools.github.io/commitizen/) CLI to lower the learning curve for the future FAANG 10x devs
- Set up [Git hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) with [Husky](https://typicode.github.io/husky/)
    - Has nothing to do with dogs
    - Pre-commit hook runs ESLint on staged files, no more nitpicky PR reviews
    - Commit Message hook runs Commitlint to stop commit messages like this: `fixplsworkplsworkabcd` :rofl: 

https://github.com/user-attachments/assets/b2200b7b-d783-4401-87e2-8741456d4e7a

- Our platform is now versioned according to the [SemVer](https://semver.org) specification with [Semantic Release](https://semantic-release.gitbook.io/semantic-release/usage/configuration)
    - It parses the conventional commit types and scope in the git commit history to auto-trigger version bumps and releases 

- What's better than one pipeline using `pnpm` you ask? Well of course it's three pipelines using `bun` :exploding_head: 

Triple the vroom vroom :robot:
 
image

   
TODO: Set up caching and run pipelines in aforementioned order rather than in parallel, but keep them on separate files. We can then say `it failed the build/test/release pipeline`. Makes communication and debugging a bit easier.

### CODE REVIEW

**Comment by MFarabi619** [comment]
Looks like `bun` isn't as compatible with `node` as I thought. I've been bunned.

Will investigate more.

**Review by HasithDeAlwis — APPROVED** [review]

**Review by JowiAoun — APPROVED** [review]

**Comment by JowiAoun** [comment]
> Looks like `bun` isn't as compatible with `node` as I thought. I've been bunned.
> 
> Will investigate more.

To add a side note, `bun` was problematic in the build but has been fixed in PR #53

**Comment by MFarabi619** [comment]
Nice, #53 links to an issue rather than a PR by the way

**Comment by JowiAoun** [comment]
After some more testing it looks like it was not fixed. ☹️
I will keep the PR to push the hotfix and get us working builds, then we can look into switching to `bun`!

**Pull request merged**
