### PR TITLE
chore!: consolidate marketing site, hacker portal app, and docs site into monorepo

### PR DESCRIPTION
**Pull request by MFarabi619**
All our code has been consolidated into an [Nx](https://nx.dev) monorepo. The migration is still in progress as the Nx task inference for the landing page, and portal are not yet working. This is okay, as it's not a gating issue and will be resolved soon.

You can see the new architecture without having to clone my branch [here](https://github.com/cuhacking/hackathon/tree/mfarabi/chore/40-consolidate-marketing-site-hacker-portal-app-and-docs-site-into-monorepo)

image

The existing configurations need to be factored out into the base configs. The `landing-page` will become `website`, and the `hackathon` should be moved over to `portal`. The docs site should also get its own `docs` directory eventually.

You can continue working as usual by just navigating into the directories first.
```
cd apps/hackathon
pnpm i
pnpm dev
````

```
cd apps/landing-page
pnpm i
pnpm dev
````

Once the migration is complete, you no longer have to do this.

TODO:
Set up the following,
- [ ] Husky
- [ ] Commitizen
- [ ] Commitlint

Semantic release is no longer necessary as Nx is capable of versioning and releasing changelogs.

- [ ] Archive [landing-page](https://github.com/cuhacking/landing-page) and move deployment. Remove the application form too.
- [ ] Rename [hackathon](https://github.com/cuhacking/hackathon) repo to `2025`

README has been given a full makeover:
image

### CODE REVIEW

**Comment by HasithDeAlwis** [comment]
Really cool work, excited to get this merged in. Do you think you can explain what the `portal` directory is?

**Comment by MFarabi619** [comment]
> Really cool work, excited to get this merged in. Do you think you can explain what the `portal` directory is?

image

In a nutshell `hackathon` is getting re-named to `portal`.

**Review by HasithDeAlwis — APPROVED** [review]
:fire::fire::fire:

**Review by cloverzer0 — APPROVED** [review]
done

**Pull request merged**
